CREATE ROLE DB_USER WITH LOGIN PASSWORD 'DB_PASSWORD' NOSUPERUSER NOCREATEDB NOCREATETABLE;
CREATE DATABASE DB_NAME OWNER DB_USER;

-- \c DB_NAME

GRANT USAGE, CREATE ON SCHEMA  app TO DB_USER; -- UŻYTKOWNIK JEST 
